version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: transcribolt_db
    environment:
      POSTGRES_DB: transcribolt
      POSTGRES_USER: transcribolt
      POSTGRES_PASSWORD: transcribolt
    volumes:
      - transcribolt_postgres_data:/var/lib/postgresql/data

  node_app:
    image: node:20
    container_name: transcribolt
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "yarn install && yarn build && yarn start"
    depends_on:
      - postgres
    ports:
      - "3001:3001"

volumes:
  transcribolt_postgres_data:
