version: '3.8'

services:
  transcribolt_db:
    image: postgres:latest
    container_name: transcribolt_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: transcribolt
      POSTGRES_USER: transcribolt
      POSTGRES_PASSWORD: transcribolt
    volumes:
      - transcribolt_postgres_data:/var/lib/postgresql/data

volumes:
  transcribolt_postgres_data:
